### PR TITLE
API: Add swagger API annotations

### LINKED ISSUE #324: Auto-generated API Documentation
Currently the API documentation is manually maintained in wiki causing following problems:
- hard to track changes of each version
- need to be managed manually by project owner/collaborator 

The problems can be resolved by auto-generating API docs from source code using [Swagger](https://github.com/swagger-api/swagger-core) or a similar tool.

### PR DESCRIPTION
**Pull request by orogvany**
Swagger can be used for client generation
and documentation generation.

fixes #324

### CODE REVIEW

**Comment by semuxproject** [comment]
We have strict policy on third party libraries:
1. Open source friendly (GPL is not)
2. Lightweight (library like guava/spring should be avoided because they're too heavy; they also depends on a lot of stuff)
3. Always code over JDK first and try not adding any dependencies (make the kernel easier to maintain and control)
4. Strictly specify the scope of dependencies (dependencies with `compile` scope will be packed and distributed, so they needs to be small).

Based on these policies, please revisit this PR

**Comment by orogvany** [comment]
Ah, my mistake.  I can fix.  Only the annotations are probably required, and thats small/apache.

good catch!

**Comment by orogvany** [comment]
Ok, errant libraries removed, only Apache and CDDL/GPLv2 with classpath exception.

**Comment by semuxproject** [comment]
Looks good. Please update LICENSE_3RD

**Comment by orogvany** [comment]
Ok.  Assumed wrongly license file was autogenerated.  
Licenses updated.

**Pull request merged**
