### PR TITLE
GUI: Add command console

### LINKED ISSUE #318: Add Debug Window Console
Hi, I would suggest that you add Debug Window Console for more option and make secretable the Private Key.
Some hacker too easy steal the private key, only click Wallet > Export Private Key.
You need to change with asterix code and user should click reaveal.

Thanks

### PR DESCRIPTION
**Pull request by orogvany**
Uses the existing REST api annotations
to create a console, as many people do not know
rest, but are familiar with the bitcoin console.

Later, more methods could be added here that are
not exposed as part of semuxAPI
like dump_priv_key or similiar.

fixes #318

### CODE REVIEW

**Comment by orogvany** [comment]
WIP as unit tests are forthcoming.  Any feedback welcome on expected features in meantime.  Thanks!

**Comment by orogvany** [comment]
@cryptokat or @semuxdev  - can remove WIP. Can be reviewed now.

**Comment by cryptokat** [comment]
Getting this error from `getBlock <number>`
selection_238

**Comment by orogvany** [comment]
Ah, yes.  That's the only overloaded method.  In your case, it's calling getBlock <hash> rather than number, and we're not validating the string is hexadecimal.  Let me dwell on that a few

**Pull request merged**
