### PR TITLE
Tools: append commit hash to version number

### PR DESCRIPTION
**Pull request by cryptokat**
This will make it more clear for developers where to address issues reported from end-users

### CODE REVIEW

**Comment by semuxproject** [comment]
Could you also update the `script/release.sh` to include the git revision? :)

**Comment by cryptokat** [comment]
Done. 

There is another issue that Appveyor is not including `.git` folder which causes build failure. Investigating now.

**Comment by cryptokat** [comment]
Issue resolved

**Comment by semuxproject** [comment]
Not working on macOS presently.

macos

**Comment by cryptokat** [comment]
fixed
screen shot 2018-01-06 at 17 46 58

**Pull request merged**
