### PR TITLE
Add Travis CI Integration

### PR DESCRIPTION
**Pull request by cryptokat**
This pull request adds github integration with https://travis-ci.org/ and https://coveralls.io/
Automated status check based on test cases can be configured for pull requests once the integration is added: https://help.github.com/articles/about-required-status-checks/

### Example Reports

- https://travis-ci.org/cryptokat/semux/builds
- https://coveralls.io/github/cryptokat/semux

### CODE REVIEW

**Comment by semuxproject** [comment]
Hi @cryptokat, we actually have a CI server, https://ci.semux.org/

I also tried the free Travis CI but it kept complaining about some of benchmark tests. Did you experience similar problems?

**Comment by cryptokat** [comment]
Hi @semuxproject 
I haven't experienced a similar issue so far. https://travis-ci.org/cryptokat/semux/jobs/301198434
If https://ci.semux.org/ can be configured for github status check and provide a better developer experience than 3rd-party services, then this pull request should be unnecessary.

**Comment by semuxproject** [comment]
I think Travis is more well-known. If you can make it work, we will merge :)

**Comment by cryptokat** [comment]
@semuxproject 
Great. I assume the integration will start working once travis-ci.org and coveralls.io are authorized to access this project.

**Comment by cryptokat** [comment]
Added eclipse format validator & license header checker.

**Comment by cryptokat** [comment]
added appveyor integration for testing under windows platform
Example report: https://ci.appveyor.com/project/cryptokat/semux/build/2%20(appveyor)

**Pull request merged**
