### PR TITLE
[wip] GUI: Show pending transactions

### LINKED ISSUE #335: Display pending transactions and rebroadcast if necessary
It would be nice to display pending transactions from this wallet.

### PR DESCRIPTION
**Pull request by orogvany**
Since there is a 30 second delay, it would be
beneficial to show pending transactions to users

fixes #335

### CODE REVIEW

**Comment by orogvany** [comment]
screen shot 2018-01-10 at 1 28 38 pm

I'm open to changing how this is notified.  We could probably update the column renderers to show them as grey rather than adding new column.

**Comment by semuxproject** [comment]
Please make the added column right aligned and fix the test case errors.

**Comment by orogvany** [comment]
ok. thanks

**Comment by orogvany** [comment]
tests pass, and column updated.

**Comment by semuxproject** [comment]
Pending transactions from pending manager are all transactions from the network, not necessarily from wallet

**Comment by orogvany** [comment]
Adding unit tests

**Pull request merged**
