### PR TITLE
Add buttons for setting the max possible amount of votes (Issue: #80)

### PR DESCRIPTION
**Pull request by phash**
Added a button for setting the max possible amount of votes 
for selected account #80 

Added a button for setting the max possible amount of unvotes 
for selected delegate

### CODE REVIEW

**Comment by semuxproject** [comment]
It's functionally correct but needs re-design. The input box get squeezed by default.

Suggest putting a small icon on the input box, instead of adding a button, as this functionality is not very critical.

error

**Comment by phash** [comment]
The TextField has a prefered and a minimal size... should not be smaller than this, if I understand correctly..
I cannot re enact the situation, where it squeezes

**Comment by semuxproject** [comment]
I'm still not very satisfied with the UX; will re-visit this PR after issue #112 is fixed.

**Comment by phash** [comment]
damn.... this did not merge correctly... :(

**Pull request closed without merging**
