### PR TITLE
 Util: fixes #260 - OSX DMG distribution 

### LINKED ISSUE #260: OSX Distribution
- [ ] Create .app bundle & .dmg image
  - https://bitbucket.org/infinitekind/appbundler
- [ ] Create homebrew formula
- [ ] QA: test osx build on travis-ci

### PR DESCRIPTION
**Pull request by orogvany**
DMG distribution with icon.  Adds license and config to DMG.

Note: Scrutinizer fails on DMG packaging, temporarily commenting out to get a clean build.  Will need to update scrutinizer to avoid dmg packaging, or update it to support.  .app file builds, so no more semux-gui.sh for osx at least.

Let me know how you want to proceed.  If you're fine with .app but no DMG, I can remove extraneous comments, or can try to figure out what mvn command to ignore for scrut builds.

bug bounty to 0x5c0c8a67ee6c14fa853c4595cd90e57359efe589 Not sure how that works.
Thanks.  Will look through others.

### CODE REVIEW

**Comment by orogvany** [comment]
The job exceeded the maximum time limit for jobs, and has been terminated.
bummer.

**Comment by semuxproject** [comment]
Travis seem to have some error. Building are extremely slow and there are huge backlogs.

Please follow our coding/git convention:
https://github.com/semuxproject/semux/blob/master/.github/contributing.md

**Comment by orogvany** [comment]
Thanks.  I did see your guide.  Mind cluing me into what I missed?

spaces, not tabs, imperative present tense, added fix #, prefixed with change portion, descriptive reasoning, small change pertinent to just the fix.

Thought I had it covered.  Sorry for the hassle.

**Comment by semuxproject** [comment]
It's fine. It's the commit message that could be improved a bit; otherwise, we have to squash all your commits into one and merge.

We just added an example here: https://github.com/semuxproject/semux/blob/develop/.github/contributing.md#contributor-workflow

**Comment by orogvany** [comment]
Ok, thanks.  I'll keep that in mind for next PR.

**Pull request merged**
