### PR TITLE
Util: Reorder public ip lookup methods

### PR DESCRIPTION
**Pull request by cryptokat**
Some ISPs/routers do not return correct results from opendns resolvers due to DNS hijacking or DNS request filtering.
http://checkip.amazonaws.com should be queried at first considering that it provides higher coverage.

### CODE REVIEW

**Comment by orogvany** [comment]
Oh. Guess it resolves but sends wrong ip?

**Comment by cryptokat** [comment]
@orogvany An user reports that his ISP redirects all unknown domain names to an advertised search engine.

**Comment by orogvany** [comment]
Shouldnt that result in falling back to aws?  Or does it match regex just with wrong data?  Fix looks fine. Just wondering why it didnt work as intended.

**Comment by cryptokat** [comment]
@orogvany The DNS hijacking doesn't make A lookup fail, instead it returns its own A record.

**Comment by orogvany** [comment]
Ah. Anything we can do to id that?  Or just assume aws will make it?  More just out of curiosity.  Presumably someone could hijack aws the same way?

**Comment by cryptokat** [comment]
@orogvany That would be out of scope of this pull request. In current implementation it requires a correct public IP advertised in handshake message for each semux node to successfully join the network. We may like to remove this restriction in the future for that kind of users

**Comment by orogvany** [comment]
Fair enough

**Comment by semuxdev** [comment]
We got more failure reports before when using amazon aws.

Many crypto users are under proxy/vpn, and the return of the Amazon AWS is not always correct in this case.

**Comment by cryptokat** [comment]
Okay. Probably we should consider a better solution that can make the P2P server get rid of 3rd-party services.

**Pull request closed without merging**
