### PR TITLE
API: Extract methods from handler into reusable location

### PR DESCRIPTION
**Pull request by orogvany**
Pull all the methods into an interface/callable methods.
This allows us to better support a command console like
other cryptos.  This could also be used later with the CLI.

SemuxAPI wasn't really an API, so it was renamed.

Also fix typo in Transaction builder.

### CODE REVIEW

**Comment by semuxproject** [comment]
This would be a good enhancement.

@cryptokat  could you also help review this?

**Comment by orogvany** [comment]
Thanks.  I have a console up and working for a second part to this.  

So you can open a window and type getInfo or getBlock 1234 etc.

Could add other methods in the future, and it'll auto update, but it's a starting point.

**Comment by orogvany** [comment]
How can I get these going through?  I can pull just API into one PR, and then movign away in the impl into another?

finally figured out how to not make merges from master show up as well. 

LMK and I can get them staged.

**Comment by semuxproject** [comment]
I will do another round of reviewing and then purge it.

**Comment by semuxproject** [comment]
There are various small issues. I will merge and fix it

**Comment by semuxproject** [comment]
Merged

**Pull request closed without merging**
